import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'accent-lime': '#C3ED3B',
        'accent-forest': '#6DAB1B',
        'surface-deep': '#061B14',
        'primary': '#506600',
        'primary-container': '#c3ed3b',
        'primary-fixed': '#c8f240',
        'primary-fixed-dim': '#add520',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#161e00',
        'on-primary-fixed-variant': '#3c4d00',
        'on-primary-container': '#536900',
        'canvas-neutral': '#F7F7F5',
        'pure-white': '#FFFFFF',
        'surface': '#f9f9f7',
        'surface-dim': '#dadad8',
        'surface-bright': '#f9f9f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4f2',
        'surface-container': '#eeeeec',
        'surface-container-high': '#e8e8e6',
        'surface-container-highest': '#e2e3e1',
        'on-surface': '#1a1c1b',
        'on-surface-variant': '#444935',
        'outline': '#757963',
        'outline-variant': '#c5c9af',
        'surface-variant': '#e2e3e1',
        'secondary': '#4d635a',
        'on-secondary': '#ffffff',
        'secondary-container': '#cde5d9',
        'on-secondary-container': '#51675e',
        'secondary-fixed': '#d0e8dc',
        'secondary-fixed-dim': '#b4ccc0',
        'on-secondary-fixed': '#0a1f18',
        'on-secondary-fixed-variant': '#364b42',
        'tertiary': '#3f6900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#adf15e',
        'on-tertiary-container': '#416d00',
        'tertiary-fixed': '#b2f662',
        'tertiary-fixed-dim': '#97d949',
        'on-tertiary-fixed': '#0f2000',
        'on-tertiary-fixed-variant': '#2e4f00',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f1ef',
        'inverse-primary': '#add520',
        'surface-tint': '#506600',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f9f9f7',
        'on-background': '#1a1c1b',
      },
      fontFamily: {
        display: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
        '3xl': '3rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'base': '8px',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      animation: {
        'float': 'float 4s ease-in-out infinite',
        'pulse-lime': 'pulse-lime 2s ease-in-out infinite',
        'gradient': 'gradient-shift 6s ease infinite',
        'marquee': 'marquee 30s linear infinite',
        'blob': 'blob 8s ease-in-out infinite',
        'rotate': 'rotate-slow 20s linear infinite',
        'shimmer': 'shimmer 2s infinite',
      },
    },
  },
  plugins: [],
};

export default config;
